name = "scrap-metal-dev"
compatibility_date = "2022-05-23"

main = "dist/worker.js"

[vars]
ORIGIN = 'http://localhost:4000'


[build]
command = "yarn build"


[dev]
port = 4000

[env.beta]
name = "scrapt-metal-beta"

[env.production]
name = "scrap-metal-production"
