name = "scrap-metal-dev"
compatibility_date = "2022-05-23"

main = "src/index.tsx"

node_compat = true

[vars]
ORIGIN = 'http://localhost:4000'

[dev]
port = 9000

[env.beta]
name = "scrapt-metal-beta"

[env.production]
name = "scrap-metal-production"
